/*!
 * Company: uelike.com
 * Developer: luoye.org
 * Date: 2013-3-11
 
 * Includes jquery
 */
 var fuck1="http://www.newsky365.com",fuck2=$(".copyright").attr("href"),fuck3=$(".copyright").attr("rel");if(!$(".copyright").length||fuck1!=fuck2||fuck3=="nofollow"||fuck3=="external nofollow"||fuck3=="nofollow external"){alert("\u535A\u4E3B\u505A\u4E86\u4E0D\u8BE5\u505A\u7684\u4E8B\uFF0C\u6240\u4EE5~");window.location="http:\/\/www.newsky365.com\/"}
self!=top&&(top.location=self.location); $(function(){function d(){if(480>=$(window).width())"20px"==$("#workcontent").css("margin-right")&&$("#workcontent").css("margin-right",0);else if($("#workshow").length)720>=$(window).width()?"lt640"!=$("body").data("data-size")&&($("#worktj").hide(),$("#workcontent").css("margin-right",20),$("body").data("data-size",",lt640")):"ge640"!=$("body").data("data-size")&&($("#worktj").show(),$("#workcontent").css("margin-right",350),$("body").data("data-size",",ge640"));else{var a=parseInt(0.95*$(window).width()/ 320);$("#headbody,#container,#navbody,#ftbody").width(320*a)}}function e(){$("#container").height()<$(window).height()-c-155&&$("#container").css("min-height",$(window).height()-c-155+"px")}var f=window.zzConfig||{};$("#sotext").focus(function(a){"\u5feb\u901f\u68c0\u7d22"==$(this).val()&&$(this).val("")});$("#sotext").blur(function(a){""==$(this).val()&&$(this).val("\u5feb\u901f\u68c0\u7d22")});var b=!1;$("#navtags").click(function(a){b||($(this).hasClass("yy2biao")?($(this).removeClass("yy2biao").addClass("yy2biao1"), b=!0,$("#cats").stop().show(400,function(){b=!1})):(b=!0,$(this).removeClass("yy2biao1").addClass("yy2biao"),$("#cats").stop().hide(400,function(){b=!1})));$(this).blur();return!1});$(".itemfoot span,#ftbody a[href='v']").click(function(a){$(this).blur();return!1});$("#goshang").click(function(a){$("html,body").animate({scrollTop:0},300);$(this).blur();return!1});$("#hbsearch form").submit(function(a){"\u5feb\u901f\u68c0\u7d22"!=$("#sotext").val()&&(document.location.href=$(this).attr("action")+encodeURIComponent($("#sotext").val())+ "/");return!1});var c=$("#header").height()+$("#navbody").height()+40;$(window).resize(function(){e();d()});d();e();$(document).height()-$(window).height()>c+80&&$(window).scroll(function(a){$(this).scrollTop()>=c?"-20px"!=$("#navfix").css("top")&&($("#navfix").css({top:-20}),$("#navfix").addClass("active")):"0px"!=$("#navfix").css("top")&&($("#navfix").css({position:"relative",top:0}),$("#navfix").removeClass("active"));100<=$(this).scrollTop()?$("#goshang").show():$("#goshang").hide()}); $("#mucomment")&&$(window).bind("message",function(a){"http://www.uehtml.com"==a.originalEvent.origin&&$("#mucomment").height(a.originalEvent.data+20)});f.tongji&&$("body").append('<div style="display:none"><script src="'+f.tongji+'" language="JavaScript">\x3c/script></div>')});
